name: giants
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  barcode_widget: 2.0.3
  cached_network_image: 3.2.1
  camera:
  carousel_slider: 4.2.1
  chewie: 1.7.1
  convert:
  country_code_picker: ^3.0.0
  easy_debounce: 2.0.1
  equatable: 2.0.5
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: 4.1.1+1
  flutter_barcode_scanner: 
    git:
      url: https://github.com/FlutterFlow/flutter_barcode_scanner
  flutter_cache_manager: 3.3.1
  flutter_native_splash: 2.3.1
  flutter_plugin_android_lifecycle: 2.0.17
  flutter_widget_from_html: ^0.10.3
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  image_picker:
  intl: 0.18.1
  io:
  json_path: 0.6.2
  mask_text_input_formatter: 2.4.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  provider: 6.0.5
  share_plus: 7.2.1
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sqflite: 2.2.6
  timeago: 3.2.2
  uni_links: ^0.5.0
  universal_io: 2.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  video_player: 2.8.1
  video_player_android: 2.4.10
  video_player_avfoundation: 2.5.1
  video_player_platform_interface: 6.2.1
  video_player_web: 2.1.2
  xml: 6.3.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  image: 4.0.17
  integration_test: 
    sdk: flutter
  lints: 3.0.0

  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  fonts:
    - family: 'Giants'
      fonts:
        - asset: assets/fonts/Arbeit-Light.otf
          weight: 300
        - asset: assets/fonts/Arbeit-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Arbeit-Regular.otf
        - asset: assets/fonts/Arbeit-BookItalic.otf
          style: italic
        - asset: assets/fonts/Arbeit-Medium.otf
          weight: 500
        - asset: assets/fonts/Arbeit-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Arbeit-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Arbeit-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Arbeit-Bold.otf
          weight: 700
        - asset: assets/fonts/Arbeit-BoldItalic.otf
          weight: 700
          style: italic
    - family: 'Giantas Denton'
      fonts:
        - asset: assets/fonts/Denton_Test_Regular_400.otf

    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
